---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: openshift-gitops
resources:
- OperatorsAppProject.yaml
- OperatorsAppSet.yaml
- OperatorInstancesAppSet.yaml
- HelmAppSet.yaml
