---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: openshift-gitops
  app.kubernetes.io/component: servicemesh
  argocd.argoproj.io/managed-by: openshift-gitops  
resources:
  - smcp-namespace.yaml
  - smcp.yaml