kind: ServiceMeshMemberRoll
apiVersion: maistra.io/v1
metadata:
  name: default
  namespace: smcp
spec:
  members:
    - servicemesh-demo
    - gallery0
    - gallery1
    - gallery2
    - gallery3
    - gallery4