kubecostProductConfigs:
  clusterName: OpenShift1
  # projectID: CLUSTER_NAME

prometheus:
  nodeExporter:
    enabled: false
  serviceAccounts:
    nodeExporter:
      create: false
  kube-state-metrics:
    disabled: true
  server:
    global:
      external_labels:
        cluster_id: OpenShift1
networkCosts:
  enabled: false
global:
  grafana:
    # TODO In OCP grafana pod fails to start becuase it requires anyuid
    # Enable via:
    #   oc label  --overwrite ns kubecost  pod-security.kubernetes.io/enforce=privileged
    #   oc adm policy add-scc-to-user anyuid -z kubecost-grafana -n kubecost
    enabled: true
    proxy: true

kubecostFrontend:
  fullImageName: "linhlamkc/cost-analyzer-frontend:prod-1.96.0"
openshiftDeployment: true

# Define persistence volume for cost-analyzer
persistentVolume:
  size: 0.2Gi
  dbSize: 32.0Gi
  enabled: true # Note that setting this to false means configurations will be wiped out on pod restart.
  # storageClass: "-" #
  # existingClaim: kubecost-cost-analyzer # a claim in the same namespace as kubecost

# Enable recommendations to be executed
# TODO: In OCP the controller fails because it needs anyuid
# Enable via:
#   oc label  --overwrite ns kubecost  pod-security.kubernetes.io/enforce=privileged
#   oc adm policy add-scc-to-user privileged -z kubecost-cluster-controller -n kubecost
#clusterController:
#  enabled: true
