---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: openshift-gitops
  app.kubernetes.io/component: kafka
  argocd.argoproj.io/managed-by: openshift-gitops  
resources:
  - kafka-namespace.yaml
  - kafka-cluster.yaml