---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: openshift-gitops
  app.kubernetes.io/component: netobserv
  argocd.argoproj.io/managed-by: openshift-gitops  
resources:
  - loki-namespace.yaml
  - loki-cmap.yaml
  - loki-deployment.yaml
  - loki-service.yaml
  - loki-storage.yaml