apiVersion: operator.serverless.openshift.io/v1alpha1
kind: KnativeKafka
metadata:
  name: knative-kafka
  namespace: knative-kafka
spec:
  broker:
    defaultConfig:
      authSecretName: ''
      bootstrapServers: 'my-cluster-kafka-bootstrap.kafka.svc:9092'
      numPartitions: 1
      replicationFactor: 1
    enabled: false
  channel:
    authSecretName: ''
    authSecretNamespace: ''
    bootstrapServers: 'my-cluster-kafka-bootstrap.kafka.svc:9092'
    enabled: true
  high-availability:
    replicas: 1
  sink:
    enabled: true
  source:
    enabled: true
