---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: openshift-gitops
  app.kubernetes.io/component: netobserv
  argocd.argoproj.io/managed-by: openshift-gitops  
resources:
  - netobserv-argocd-clusterrole.yaml
  - netobserv-namespace.yaml
  - netobserv-subscription.yaml
  - netobserv-flowcollector.yaml
