apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-gitops-openshift-gitops-argocd-application-controller
rules:
- apiGroups:
  - flows.netobserv.io
  resources:
  - '*'
  verbs:
  - '*'