apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/amq-streams.openshift-operators: ""
  name: amq-streams
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: amq-streamsamq-streams-cluster-operator-v2.1.0-6-7f4999fb7c-qzk9k
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  config:
    env:
    - name: FIPS_MODE
      value: disabled