---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: openshift-gitops
  app.kubernetes.io/component: servicemesh
  argocd.argoproj.io/managed-by: openshift-gitops  
resources:
  - openshift-operators-redhat-namespace.yaml
  - openshift-distributed-tracing-namespace.yaml
  - openshift-distributed-tracing-operator-group.yaml
  - openshift-operators-redhat-operator-group.yaml
  - elasticsearch-subscription.yaml
  - jaeger-subscription.yaml
  - kiali-subscription.yaml
  - servicemsh-subscription.yaml
  - servicemesh-clusterrole.yaml
  - servicemesh-clusterrole-binding.yaml