apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: integration-gitops-cluster-role
rules:
- apiGroups: ["installations.integration.redhat.com"]
  resources: ["*"]
  verbs: ["*"]
