apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kubecost
spec:
  port:
    targetPort: 9090
  to:
    kind: Service
    name: kubecost-cost-analyzer
    weight: 100
  wildcardPolicy: None
