apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: knative-gitops-cluster-role
rules:
- apiGroups: ["operator.knative.dev"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["operator.serverless.openshift.io"]
  resources: ["*"]
  verbs: ["*"]
