---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: openshift-gitops
  app.kubernetes.io/component: knative
  argocd.argoproj.io/managed-by: openshift-gitops  
resources:
  - knative-namespace.yaml
  - knative-subscription.yaml
  - knative-operator-group.yaml
  - knative-eventing.yaml
  - knative-serving.yaml
  - knative-kafka.yaml
  - knative-argocd-clusterrole-binding.yaml
  - knative-argocd-clusterrole.yaml