apiVersion: v1
kind: Pod
metadata:
  name: loki
  namespace: loki
  labels:
    app: loki
spec:
  # securityContext:
  #   runAsGroup: 0
  #   runAsUser: 1000
  #   fsGroup: 1000
  volumes:
    - name: loki-store
      persistentVolumeClaim:
        claimName: loki-store
    - name: loki-config
      configMap:
        name: loki-config
  containers:
    - name: loki
      image: grafana/loki:2.5.0
      volumeMounts:
        - mountPath: "/loki-store"
          name: loki-store
        - mountPath: "/etc/loki"
          name: loki-config